import { useState } from 'react';
import { Alert, Button, Card, Form, ProgressBar } from 'react-bootstrap';
import client, { errorMessage } from '../api/client';
import PageIntro from '../components/PageIntro';

export default function ChapterSummaryQuiz() {
  const [file, setFile] = useState(null); const [length, setLength] = useState('medium'); const [data, setData] = useState(null); const [answers, setAnswers] = useState({}); const [submitted, setSubmitted] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [progress, setProgress] = useState(0);
  const submit = async (event) => { event.preventDefault(); if (!file) { setError('Please choose a PDF file.'); return; } setError(''); setBusy(true); setProgress(15); const body = new FormData(); body.append('file', file); body.append('length', length); try { const { data: response } = await client.post('/chapters/summarize', body, { headers: { 'Content-Type': 'multipart/form-data' }, onUploadProgress: (e) => setProgress(e.total ? Math.round((e.loaded / e.total) * 65) : 35) }); setProgress(100); setData(response); setAnswers({}); setSubmitted(false); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } };
  const correct = data?.questions.reduce((total, q, i) => total + (answers[i] === q.correctIndex ? 1 : 0), 0) || 0;
  return <><PageIntro eyebrow="PDF CHAPTER SUMMARIZER" title="Read less. Retain more.">Upload a text-based chapter PDF and get a digestible summary plus five questions to test your understanding.</PageIntro><Card className="tool-card mb-4"><Card.Body className="p-4"><Form onSubmit={submit}><div className="upload-row"><Form.Group className="flex-grow-1"><Form.Label>Chapter PDF <span className="text-muted">(max 10 MB)</span></Form.Label><Form.Control type="file" accept="application/pdf,.pdf" onChange={(e) => setFile(e.target.files[0])} /></Form.Group><Form.Group><Form.Label>Summary length</Form.Label><Form.Select value={length} onChange={(e) => setLength(e.target.value)}><option value="short">Short · ~100 words</option><option value="medium">Medium · ~250 words</option><option value="long">Long · ~500 words</option></Form.Select></Form.Group><Button className="primary-button" type="submit" disabled={busy}>{busy ? 'Processing…' : 'Create summary'}</Button></div>{busy && <div className="mt-3"><div className="d-flex justify-content-between small text-muted mb-1"><span>Extracting and generating your quiz…</span><span>{progress}%</span></div><ProgressBar now={progress} animated /></div>}{error && <Alert className="mt-3 mb-0" variant="danger">{error}</Alert>}</Form></Card.Body></Card>
  {data && <><Card className="summary-card mb-4"><Card.Body className="p-4 p-md-5"><p className="eyebrow">{data.filename}</p><h2>Chapter summary</h2><p className="summary-text">{data.summary}</p><Button variant="outline-success" size="sm" onClick={() => navigator.clipboard.writeText(data.summary)}>Copy summary</Button></Card.Body></Card><Card className="quiz-card"><Card.Body className="p-4 p-md-5"><div className="d-flex justify-content-between align-items-center"><div><p className="eyebrow">KNOWLEDGE CHECK</p><h2>Test yourself</h2></div>{submitted && <div className="score-pill">{correct}/{data.questions.length} correct</div>}</div>{data.questions.map((question, qIndex) => <div className="question" key={`${question.question}-${qIndex}`}><strong>{qIndex + 1}. {question.question}</strong>{question.options.map((option, optionIndex) => <Form.Check key={option} type="radio" name={`question-${qIndex}`} label={option} disabled={submitted} checked={answers[qIndex] === optionIndex} onChange={() => setAnswers({ ...answers, [qIndex]: optionIndex })} className={submitted ? (optionIndex === question.correctIndex ? 'correct-answer' : answers[qIndex] === optionIndex ? 'wrong-answer' : '') : ''} />)}{submitted && <small className="answer-note">Correct answer: {question.options[question.correctIndex]}</small>}</div>)}<Button className="primary-button" disabled={submitted || Object.keys(answers).length !== data.questions.length} onClick={() => setSubmitted(true)}>{submitted ? 'Quiz submitted' : 'Submit quiz'}</Button></Card.Body></Card></>}</>;
}
