import { useEffect, useState } from 'react';
import { Card, Nav, Spinner, Tab, Table } from 'react-bootstrap';
import client from '../api/client';
import PageIntro from '../components/PageIntro';
import LogoMark from '../components/LogoMark';

const formatDate = (value) => value ? new Date(value).toLocaleString() : '';
export default function History() {
  const [data, setData] = useState(null);
  useEffect(() => { Promise.all([client.get('/content/history'), client.get('/plagiarism/history'), client.get('/chapters/history')]).then(([generations, checks, chapters]) => setData({ generations: generations.data, checks: checks.data, chapters: chapters.data })).catch(() => setData({ generations: [], checks: [], chapters: [] })); }, []);
  return <><PageIntro eyebrow="YOUR ARCHIVE" title="Everything you’ve explored.">Revisit past drafts, originalities checks, chapter summaries, and quizzes.</PageIntro>{!data ? <div className="text-center py-5"><Spinner animation="border" /></div> : <Tab.Container defaultActiveKey="generations"><Nav variant="pills" className="history-tabs mb-4"><Nav.Item><Nav.Link eventKey="generations">Generations ({data.generations.length})</Nav.Link></Nav.Item><Nav.Item><Nav.Link eventKey="checks">Originality checks ({data.checks.length})</Nav.Link></Nav.Item><Nav.Item><Nav.Link eventKey="chapters">Chapter summaries ({data.chapters.length})</Nav.Link></Nav.Item></Nav><Tab.Content><Tab.Pane eventKey="generations"><Card className="history-card"><Card.Body>{data.generations.length ? data.generations.map((item) => <article className="history-item" key={item.id}><div><p className="eyebrow">{item.contentType} · {item.tone}</p><h3>{item.prompt}</h3><p>{item.content.slice(0, 220)}…</p></div><small>{item.wordCount} words<br />{formatDate(item.createdAt)}</small></article>) : <Empty text="Your generated drafts will appear here." />}</Card.Body></Card></Tab.Pane><Tab.Pane eventKey="checks"><Card className="history-card"><Card.Body>{data.checks.length ? <Table responsive><thead><tr><th>Verdict</th><th>Score</th><th>Checked</th></tr></thead><tbody>{data.checks.map((item) => <tr key={item.id}><td>{item.verdict}</td><td className="fw-bold">{item.score}%</td><td>{formatDate(item.createdAt)}</td></tr>)}</tbody></Table> : <Empty text="Your originality checks will appear here." />}</Card.Body></Card></Tab.Pane><Tab.Pane eventKey="chapters"><Card className="history-card"><Card.Body>{data.chapters.length ? data.chapters.map((item) => <article className="history-item" key={item.id}><div><p className="eyebrow">CHAPTER SUMMARY</p><h3>{item.filename}</h3><p>{item.summary.slice(0, 220)}…</p></div><small>{formatDate(item.createdAt)}</small></article>) : <Empty text="Your chapter summaries will appear here." />}</Card.Body></Card></Tab.Pane></Tab.Content></Tab.Container>}</>;
}
function Empty({ text }) { return <div className="empty-inline"><LogoMark /><p>{text}</p></div>; }
